### PR TITLE
Translations for Catalan and Spanish

### PR DESCRIPTION
**Pull request by laz08**
This pull request consists on the full translation of the app to both Catalan and Spanish.

The default strings.xml (in English) has been modified as well to change some strings and make them translatable, for the ordering of the words was not correct (i.e. "Y Set" becomes "Conjunt Y").

I hope everything is correct on the merge.
Any suggestions are welcome.

And thanks for having created the app!

### CODE REVIEW

**Comment by theblackwidower** [comment]
This is brilliant! I'm extremely happy! But I'll be honest, I'm guessing you used the template I posted on Gist. Which is great but, and this is my fault, it was slightly out of date. I have since added a few more items. I added a Log Details feature, the title of that needs translation, and there are two new sets of vocab questions. 

I'm not going to ask you to do any of that, because it's not really mandatory for the app to work in Spanish and Catalan. Just one line still in English, and two fewer sets of vocabulary questions. I doubt anyone's going to get upset over that.

I'd be more concerned for the moment when I finally merge the kanji questions branch. We'll have 240 items still in English. If you don't want to bother with that though, I don't blame you.

**Comment by laz08** [comment]
> [...] I'm guessing you used the template I posted on Gist. Which is great but, and this is my fault, it was slightly out of date. I have since added a few more items.

Actually, I did not! I forked the whole project 3 days ago and then copied the files into their corresponding directories.

However, I've noticed that 2 days ago you added some vocab, which I did not notice, so I guess it's kind of my fault for not checking it again before creating the pull request. Well.

If I have some spare time I'll translate the new vocabulary added. Maybe even do some corrections on some strings for normalization/adequacy on Spanish and Catalan.

I doubt I'll have enough spare time for translating 240, honestly. Maybe I should first learn fully the Kana myself :)

**Comment by laz08** [comment]
Well, as promised, the missing translations have been done.

For future work it would be cool to reorder the strings.xml that I generated with Android Studio so that they follow the order used on the original strings.xml.

Some adequacy/normalization has been done on the Logs part, for the straightforward translation of that word does not sound OK in Spanish and Catalan.

**Comment by theblackwidower** [comment]
Do not worry about the kanji. It hasn't even been integrated into the develop branch yet. It might not even make it into the next release, I don't know. But if it is, it'll just mean any Spanish/Catalan users will be expected to answer any kanji questions in English. That might not be a huge problem, they can just not select the kanji. 

The only major issue I see stemming from this is if they select some vocabulary questions, and some kanji questions, and they see a kanji, and the correct Spanish translation happens to appear on the multiple choice screen, and they select it, it'll be registered as incorrect even though it is actually correct. Might be confusing.

I could just add a hook that disables Kanji for those languages. But it'll be something I'll have to manually put in. Probably won't be a huge ask, won't know until I tried it.

Again, genuinely, don't worry about it. I'm not going to ask you to translate 240 items. It's a big ask anyway. But I forgot, I wanted to thank you for the work you've already done. I greatly appreciate it. Thank you!

**Comment by theblackwidower** [comment]
Noticed what I think is a slight oversight: https://github.com/theblackwidower/KanaQuiz/blob/90db8829b85f21d8741ef7f4e051d9f067147b1e/app/src/main/res/values-es-rES/strings.xml#L16

It's the line telling the user they should be selecting the translation in their local language. But if I'm not mistaken 'inglés' means English. Should be Spanish or 'español', shouldn't it? 

I bow before your superior knowledge on this.

**Comment by laz08** [comment]
> It's the line telling the user they should be selecting the translation in their local language. But if I'm not mistaken 'inglés' means English. Should be Spanish or 'español', shouldn't it?

You are right. That's what happens when you translate something while having your mind divided, paying attention to other things... Good catch, thanks for the tip.
It should be correct now.

I have also corrected (again) some strings. I didn't notice some misspellings or just direct mistranslations... 

And I hope you don't mind but I have also abstracted a string from the katakana.xml to strings.xml, so that it is translatable to other languages:
`<string name="set_11_title">Extended Katakana</string>`

(I'm not sure how to link to a line of code of a specific line from a specific commit like you did)

And I think that's all I had to change/take a look at. I understand the concern on the multiple choice screen, but to be honest, I have not taken a close look on your implementation so I don't think I'm able to propose any sensible solution. As you have mentioned, checking whether a kanji has been localized may be a solution. Not sure about how efficient that could be, tho.

>But I forgot, I wanted to thank you for the work you've already done. I greatly appreciate it. Thank you!

Don't mention it, it's not a problem. I just wanted to help on a useful project so that it can reach more people. 

Hopefully if I have more time in the future I would like to be able to help you with the UI, implementation and such. For now, I'll stick to those 2 translations.

**Comment by theblackwidower** [comment]
Got some news. There's a major update, I added several new strings to the resource file, and I think it might help if they're translated. I wouldn't worry about the kanji or vocab stuff, just the ones for the Extended Katakana, Font Provider, and Themes. There are only 22 that are really relevant.

I was hoping on getting a release ready before Christmas. Not to put any pressure on you. If I send out a new release before you can translate the new stuff, I can issue a hotfix without any trouble.

If you're too busy, don't worry about it.

**Comment by theblackwidower** [comment]
By the way, if you are going to update the translation, please start from the release-0.14 branch, or (if that's gone) the master branch. That way, if it doesn't make the next release, I can quickly and easily put out a hotfix. I genuinely don't know if I'm going to make a release tonight, or later in the week.

**Comment by laz08** [comment]
Ok. I honestly doubt I'll have the time to work on this until the 27st or onward. The 24th, 25th and 26th are Holidays here spent with family so... Not the best days to work on this. But if I get the a tiny slot to at least translate those 22 strings I'll do so.

I'll take the branch/release thing into account.

**Pull request merged**
